spring:
  profiles:
    active: local
#  datasource:
#    username: postgres
#    password: postgres
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#    properties:
#      hibernate:
#        jdbc.lob.non_contextual_creation: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        ddl-auto: none
  mail:
    password:
    port: 1025
    # TODO change
    username: demo@gmail.com
  servlet:
    multipart:
      max-file-size: 500KB
      max-request-size: 500KB

application:
  security:
    cookie:
      expiration: 1800000
    token:
      secret: zdtlD3JK56m6wTTgsNFhqzjqP
      expiration: 1800000
      refresh:
        expiration: 7200000
  url:
    token:
      expiration: 1440

---
spring:
  config:
    activate:
      on-profile: local
#  datasource:
#    url: jdbc:postgresql://localhost:5432/demo
  mail:
    ## host: mailhog
    host: localhost
application:
  security:
    cookie:
      secure: false
  url:
    baseUrl: http://localhost:8080


